name: fake_store_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: 6.1.2
  dartz: 0.10.1
  fake_store_ds:
    git:
      url: https://github.com/chrisr04/fake_store_ds
      ref: v0.0.4
  fake_api:
    git:
      url:  https://github.com/chrisr04/fake_api
      ref: v0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: 1.0.4
  mocktail_image_network: 1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
